server:
  port: 9999
eureka:
  instance:
      hostname: ${HOST_URL}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_URL:eureka}:${EUREKA_PORT:8761}/eureka/

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: file://config
          
logging:
  level:
    com.netflix.eureka: info